'use strict';

function buildPrompt(raw, categories) {
  return `You are a structured data extractor for BinBag, the AI ecosystem directory.

Given the raw information below about an AI-related item, extract and return a JSON object with EXACTLY these fields:

{
  "name":              string  -- clean product/paper/course/tool name,
  "short_description": string  -- 1 sentence, max 120 chars, plain English, no marketing hype,
  "full_description":  string  -- 3-5 sentences covering what it does, who its for, and what makes it notable. Mark as AI-generated if you are generating this.,
  "ai_generated_description": boolean -- true if full_description was generated by you rather than extracted verbatim from source,
  "item_type":         string  -- one of: tool, research, learning, job, community, dataset, framework, event, podcast,
  "category":          string  -- one of: ${categories.join(', ')},
  "subcategory":       string  -- most specific subcategory, lowercase-hyphen format,
  "pricing_model":     string  -- one of: free, freemium, paid, open-source (null if not applicable),
  "tags":              string[]-- 3-6 lowercase descriptive tags,
  "website_url":       string  -- canonical URL,
  "official_pricing_url": string | null -- direct pricing page URL if distinct from website_url,
  "logo_url":          string | null -- direct image URL for logo,
  "screenshot_url":    string | null -- URL to a screenshot or preview image if available,
  "authors":           string | null -- author names for research papers,
  "location":          string | null -- location for jobs/events,
  "event_date":        string | null -- ISO date for events,
  "launch_date":       string | null -- ISO date of initial release/launch
}

Rules:
- Return ONLY valid JSON. No markdown fences, no extra text.
- If a field cannot be determined, use null.
- For item_type: papers/preprints -> "research"; libraries/repos -> "framework"; tutorials/courses -> "learning"; job postings -> "job"; Discord/Reddit -> "community"; training data -> "dataset"; recurring audio/text content -> "podcast" or "learning"; installable apps/APIs -> "tool".
- For category, choose the MOST specific match.
- full_description should be substantive and useful — not just a repeat of short_description.
- Do not fabricate facts; base everything on the provided input.

Input data:
Name: ${raw.name || '(unknown)'}
Description: ${raw.description || '(none)'}
Website: ${raw.website_url || '(none)'}
Source: ${raw.source}
Tags: ${raw.tags ? raw.tags.join(', ') : '(none)'}
Pricing hint: ${raw.pricing || '(unknown)'}
Authors: ${raw.authors || '(none)'}`;
}

module.exports = { buildPrompt };